---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eve-scrap
spec:
  selector:
    matchLabels:
      app: eve-scrap
  template:
    metadata:
      labels:
        app: eve-scrap
    spec:
      containers:
      - name: eve-scrap
        image: sophaskins/eve-scrap
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: eve-scrap
  name: eve-scrap
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: http
    name: http
  selector:
    app: eve-scrap

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: eve-scrap
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - eve-scrap.sophaskins.net
    secretName: eve-scrap-tls
  rules:
  - host: eve-scrap.sophaskins.net
    http:
      paths:
      - path: /
        backend:
          serviceName: eve-scrap
          servicePort: 80
